export { default as Home } from './home/Home'
export { default as Discovery } from './discovery/Discovery'
export { default as Education } from './education/Education'
export { default as Map } from './map/Map'
export { default as News } from './news/News'
export { default as OnBoarding } from './on-boarding/OnBoarding'
export { default as Splash } from './splash/Splash'
export { default as Login } from './login/Login'
